# .github/workflows/deploy.yml

name: Django Deployment

on:
  push:
    branches:
      - ec2_django

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up SSH and add the key
    - name: Set up SSH
      env: 
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      
      run: |
        # Create the .ssh directory if it doesn't exist
        mkdir -p ~/.ssh
        # Write the SSH private key to a file and preserve line breaks
        echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ssh_key.pem
        # Ensure the key has the correct permissions
        chmod 400 ssh_key.pem
        # Add EC2 host to known hosts to avoid host verification prompts
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    # Step 3: Copy the project files to the EC2 instance using SCP (Secure Copy)
    - name: Copy files via SCP
      run: |
        scp -r -o StrictHostKeyChecking=no ./ ubuntu@${{ secrets.EC2_HOST }}:/path/to/django/project

    # Step 4: Run commands on the EC2 instance to set up the Django application
    - name: Run SSH Commands
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Change to the Django project directory
          cd /path/to/django/project
          # Activate the virtual environment
          source /path/to/venv/bin/activate
          # Install required Python packages
          pip install -r requirements.txt
          # Run Django database migrations
          python manage.py migrate
          # Collect static files for Django
          python manage.py collectstatic --noinput
          # Restart the Gunicorn service (WSGI server)
          sudo systemctl restart gunicorn
          # Restart the Nginx web server
          sudo systemctl restart nginx
        EOF
