# .github/workflows/deploy.yml

name: Django Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files via SCP ##SCP (Secure Copy Protocol) to securely transfer files from the local GitHub Actions runner to the EC2 instance
      run: |
        scp -r -o StrictHostKeyChecking=no ./ ubuntu@${{ secrets.EC2_HOST }}:/path/to/django/project

    - name: Run SSH Commands
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'     #opens an SSH (Secure Shell) connection to the EC2 instance.
          cd /path/to/django/project 
          source /path/to/venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn  #Restarts the Gunicorn service, which is the WSGI server used to serve the Django app
          sudo systemctl restart nginx
        EOF
